services:
  backend:
    image: ghcr.io/juniqu-e/guestbook-cicd/backend:${IMAGE_TAG:-latest}
    container_name: guestbook-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JPA_SHOW_SQL=false
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_WEB=WARN
      - H2_CONSOLE_ENABLED=false
    restart: unless-stopped
    networks:
      - guestbook-network

  frontend:
    image: ghcr.io/juniqu-e/guestbook-cicd/frontend:${IMAGE_TAG:-latest}
    container_name: guestbook-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend  # 단순 의존성만, 헬스체크 없음
    restart: unless-stopped
    networks:
      - guestbook-network

networks:
  guestbook-network:
    driver: bridge